// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGjI1AtK_1RVWbkI2XPlIrFT1FQhsPwpg',
    appId: '1:224128098759:web:815883a3a984bbd1fb79e2',
    messagingSenderId: '224128098759',
    projectId: 'company-erp-19499',
    authDomain: 'company-erp-19499.firebaseapp.com',
    storageBucket: 'company-erp-19499.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjpYFWzxmavBIdrFxAUyaaKsQWgkFpwas',
    appId: '1:224128098759:android:7235aab37743d6c4fb79e2',
    messagingSenderId: '224128098759',
    projectId: 'company-erp-19499',
    storageBucket: 'company-erp-19499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR6zplP4_UVMUw68UkXuPKS4eqqkVTN1M',
    appId: '1:224128098759:ios:17533cdaacaf09f0fb79e2',
    messagingSenderId: '224128098759',
    projectId: 'company-erp-19499',
    storageBucket: 'company-erp-19499.firebasestorage.app',
    iosBundleId: 'com.example.projectbtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGjI1AtK_1RVWbkI2XPlIrFT1FQhsPwpg',
    appId: '1:224128098759:web:b3e32b210038b0d1fb79e2',
    messagingSenderId: '224128098759',
    projectId: 'company-erp-19499',
    authDomain: 'company-erp-19499.firebaseapp.com',
    storageBucket: 'company-erp-19499.firebasestorage.app',
  );
}
